services:
  php:
    image: yiisoftware/yii2-php:8.2-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    depends_on:
      - db
    networks:
      - yii_post

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: yii2basic
      MYSQL_USER: yii2basic
      MYSQL_PASSWORD: 'yii2basic'
      MYSQL_ROOT_PASSWORD: 'yii2basic'
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - yii_post

  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - yii_post
volumes:
  mysql_data:

networks:
  yii_post:
    driver: bridge